import { createApp } from 'vue'

import ExcelWorkspaceApp from './app/ExcelWorkspaceApp.vue'
import './style.css'
import './styles/workspace-files.css'
import './styles/workspace-chat.css'
import './styles/auth-shell.css'
import './styles/icon-system.css'
import './styles/upload-workbook.css'
import './styles/chat-message.css'
import './styles/excel-grid.css'
import './styles/file-management.css'
import './styles/document-summary.css'
import './styles/pdf-knowledge.css'
import './styles/pdf-workspace-alignment.css'
import './styles/pdf-management-alignment.css'
import './styles/pdf-shared-alignment.css'
import './styles/pdf-chat-sessions.css'
import './styles/workspace-shell.css'
import './styles/file-workspace-template.css'

createApp(ExcelWorkspaceApp).mount('#app')
